# Generated by Django 5.1.3 on 2024-11-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='rating',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='imdb_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
